DROP TABLE IF EXISTS personal_information CASCADE;
CREATE TABLE personal_information (
    Customer_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    Customer_Name VARCHAR(255) NOT NULL,
    Customer_Surname VARCHAR(255) NOT NULL,
    Customer_Primary_Email VARCHAR(255) NOT NULL,
    Customer_Primary_Phone VARCHAR(255) NOT NULL,
    CHECK (Customer_Name ~ '^([А-Я]{1}[а-яё\- ]{0,}|[A-Z]{1}[a-z\- ]{0,})$'),
    CHECK (Customer_Surname ~  '^([А-Я]{1}[а-яё\- ]{0,}|[A-Z]{1}[a-z\- ]{0,})$'),
    CHECK (Customer_Primary_Email ~ '^((([0-9A-Za-z]{1}[-0-9A-z\.]{0,}[0-9A-Za-z]{1})|([0-9А-Яа-я]{1}[-0-9А-я\.]{0,}[0-9А-Яа-я]{1}))@([-A-Za-z]{1,}\.){1,2}[-A-Za-z]{2,})$'),
    CHECK (Customer_Primary_Phone ~ '^((\+7)+([0-9]){10})$')
);

DROP TABLE IF EXISTS cards CASCADE;
CREATE TABLE cards (
    Customer_Card_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    Customer_ID BIGINT NOT NULL REFERENCES personal_information (Customer_ID)
);

DROP TABLE IF EXISTS sku_groups CASCADE;
CREATE TABLE sku_groups (
    Group_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    Group_Name TEXT,
    CHECK (Group_Name ~ '^[а-яА-ЯёЁ0-9!@#$%^&*()_+\-=\[\]{};:"\\|,.<>\/?]*|[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};:"\\|,.<>\/?]*$')
);

DROP TABLE IF EXISTS commodity_matrix CASCADE;
CREATE TABLE commodity_matrix (
    SKU_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    SKU_Name TEXT NOT NULL,
    Group_ID BIGINT NOT NULL REFERENCES sku_groups (Group_ID),
    CHECK (SKU_Name ~ '^[а-яА-ЯёЁ0-9!@#$%^&*()_+\-=\[\]{};:"\\|,.<>\/?]*|[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};:"\\|,.<>\/?]*$')
);

DROP TABLE IF EXISTS stores CASCADE;
CREATE TABLE stores (
    Transaction_Store_ID BIGINT NOT NULL,
    SKU_ID BIGINT NOT NULL REFERENCES commodity_matrix (SKU_ID),
    SKU_Purchase_Price DOUBLE PRECISION NOT NULL,
    SKU_Retail_Price DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (Transaction_Store_ID, SKU_ID)
);

DROP TABLE IF EXISTS transactions CASCADE;
CREATE TABLE transactions (
    Transaction_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    Customer_Card_ID BIGINT NOT NULL REFERENCES cards (Customer_Card_ID),
    Transaction_Summ DOUBLE PRECISION NOT NULL,
    Transaction_DateTime TIMESTAMP WITH TIME ZONE,
    Transaction_Store_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS checks CASCADE;
CREATE TABLE checks (
    Transaction_ID BIGINT NOT NULL REFERENCES transactions (Transaction_ID),
    SKU_ID BIGINT NOT NULL REFERENCES commodity_matrix (SKU_ID),
    SKU_Amount NUMERIC NOT NULL,
    SKU_Summ NUMERIC NOT NULL,
    SKU_Summ_Paid NUMERIC NOT NULL,
    SKU_Discount NUMERIC NOT NULL,
    PRIMARY KEY (Transaction_ID, SKU_ID)
);

DROP TABLE IF EXISTS date_of_analysis_formation CASCADE;
CREATE TABLE date_of_analysis_formation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    Analysis_Formation TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
SET datestyle = 'Euro';
